# Generated by Django 6.0.4 on 2026-05-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='category_id',
            new_name='category',
        ),
    ]
