# Generated by Django 5.2.13 on 2026-05-21 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0003_alter_menu_options_alter_menu_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='menu_category',
            options={},
        ),
    ]
