# Generated by Django 6.0.4 on 2026-05-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pay_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.IntegerField()),
                ('pay_option', models.CharField()),
                ('min_pay', models.IntegerField()),
            ],
        ),
    ]
