# Generated by Django 6.0.4 on 2026-05-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_method',
            name='min_pay',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pay_method',
            name='pay_id',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pay_method',
            name='pay_option',
            field=models.CharField(max_length=50),
        ),
    ]
