# Generated by Django 6.0.4 on 2026-05-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0002_alter_pay_method_min_pay_alter_pay_method_pay_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_method',
            name='min_pay',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pay_method',
            name='pay_id',
            field=models.IntegerField(),
        ),
    ]
