# Generated by Django 6.0.4 on 2026-05-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0003_alter_pay_method_min_pay_alter_pay_method_pay_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay_method',
            name='pay_id',
        ),
        migrations.AddField(
            model_name='pay_method',
            name='max_pay',
            field=models.IntegerField(default=1000),
        ),
    ]
