# Generated by Django 5.2.13 on 2026-05-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0004_remove_pay_method_pay_id_pay_method_max_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_method',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
