# Generated by Django 6.0.4 on 2026-05-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0005_alter_pay_method_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_method',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
